import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin,AiFillTwitterCircle,AiFillFacebook,AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import md from '../public/md smile.jpg'

import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';

import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react'





export default function Home() {
  const [darkMode,setDarkMode]=useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Tailwind Site 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
           <nav className='py-10 mb-10 flex justify-between'>
              <h1 className='text-xl font-burtons dark:text-white'>Made by 💻MDK </h1>
              <ul className='flex items-center'>
                  <li> <BsFillMoonStarsFill className='cursor-pointer text-2xl mr-2 dark:text-white'  onClick={()=>setDarkMode(!darkMode)}/> </li>
                  
                  <li>
                    <a href='/' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white 
                    px-4 py-2 rounded ml-4' >Resume </a>
                  </li>    
              </ul>
           </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-700 font-medium md:text-6xl'>Mauro Kane</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and <span className='italic bold font-bold'> wanna be designer</span> 😋</h3>
            <p className='text-xl my-5 mx-auto leading-8 text-gray-800 md:text-xl max-w-xl dark:text-white'>
              Freelancer providing services for programming and sometimes design content needs. 
              Join me below and let's get cracking!
            </p>
          </div>

          <div className='text-3xl flex justify-center gap-3 text-gray-600 dark:text-white'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillFacebook/>
            <AiFillYoutube/>
          </div>

          <div className='relative mx-auto w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96'>  
            <Image src={md}  className='rounded-full' />
          </div>
        
        </section>
        
        <div className='flex flex-col'>
          <h3 className='text-3xl py-1 mx-auto dark:text-white'>Services I offer </h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
            Since the beginning of my journey as a Freelance Developer, I've done remote for 
            <span className='text-teal-500 font-bold'> agencies</span> consulted for 
            <span className='text-teal-500 font-bold'> startups</span> and collaborated with talanted people to create digital products for 
            both bussiness and consumer use.   
          </p>
        </div>

        <section className='p-1 gap-3 md:flex'>
          
          <div className='card-service-style'>
            <Image src={design} width={100} height={100}/>
            <h3 className='card-service-h3'>Beautiful Designs</h3>
            <p  className='py-2 dark:text-white'> Creating elegant designs suited for your needs following core design theory </p>
            <h4 className='card-service-h4'>Design tools I use </h4>
            <p className='card-service-p'>Photoshop</p>
            <p className='card-service-p'>Figma</p>
            <p className='card-service-p'>Illustrator</p>
          </div> 

          <div className='card-service-style'>
            <Image src={code} width={100} height={100}/>
            <h3 className='card-service-h3'>Programming </h3>
            <p className='py-2 dark:text-white'> Making beautiful and easy to use Apps with the most recent Technology's </p>
            <h4 className='py-4 text-teal-600 font-semibold'>Design tools I use </h4>
            <p className='card-service-p'>Framer Motion</p>
            <p className='card-service-p'>React Js</p>
            <p className='card-service-p'>Tailwind CSS</p>
          </div>    

          <div className='card-service-style'>
            <Image src={consulting} width={100} height={100}/>
            <h3 className='card-service-h3'>Consulting</h3>
            <p className='py-2 dark:text-white'> Helping you determine the technology capabilities, systems and people you need to succeed </p>
            <h4 className='py-4 text-teal-600 font-semibold'>Design tools I use </h4>
            <p className='card-service-p'>Project</p>
            <p className='card-service-p'>Visio</p>
            <p className='card-service-p'>Illustrator</p>
          </div>    

        </section>
        
        <section>
          
          <div className='flex flex-col items-center'>
            <h2 className='text-3xl py-1 dark:text-white'>Portofolio</h2>
            <p className='text-md py-2 leading-8 text-gray-800 font-semibold dark:text-white'> Take a look at of my work </p>
          </div>

          <div className='card-project-style' >
              <div className='basis-1/3 flex-1'> <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' /> </div>
              <div className='basis-1/3 flex-1'> <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/> </div>
              <div className='basis-1/3 flex-1'> <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/> </div>
              <div className='basis-1/3 flex-1'> <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/> </div>
              <div className='basis-1/3 flex-1'> <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/> </div>
              <div className='basis-1/3 flex-1'> <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/> </div>

          </div>  
        </section>
      
      </main>   
      
    </div>
  )
}
